### ISSUE TITLE
Fit to Height no longer works

### ISSUE THREAD

**Issue by Kriswilly** [valentindb/fit-to-artboard#1]
With a XD update the fit to height no longer works, it is now the short cut for horizontal scrolling.

**Comment by valentindb** [comment]
Thanks for the report! I am thinking about switching it to `CMD+MAJ+J` - Would that work for you?

**Comment by Kriswilly** [comment]
That command would be great, thank you for the speedy reply.

**Comment by valentindb** [comment]
No problem. Changed it. You can download the raw files here and place it in your plugin folder if you need it frequently. 
I am updating the plugin on the Adobe Console, although the update might take a while to be reviewed on Adobe side.

Thanks for using the plugin :)
